// src/data/orthoReference.ts
//
// Ortho-rehab reference data for SZMC ward (post-hip, post-knee, post-spine cohort).
// Source-of-truth: ~/.claude/skills/rehab-quickref/ + ~/.claude/skills/ortho-reference/.
// Generated from WARD_HELPER_ORTHO_REHAB_BRIEF v2 (2026-05-10).
//
// If the upstream skills update, re-export — do not edit this file in isolation.
// Hebrew strings preserved as-is UTF-8. No Unicode arrows, no markdown bold,
// no `--` dividers (Chameleon EMR paste hygiene; see src/i18n/bidi.ts).

export interface HipFractureProcedure {
  readonly fractureLocation: string;
  readonly subtype: string;
  readonly procedure: string;
  readonly rationale: string;
  readonly approach?: ReadonlyArray<string>;
}

export interface DemandStratification {
  readonly purpose: string;
  readonly higherDemand: ReadonlyArray<string>;
  readonly lowerDemand: ReadonlyArray<string>;
  readonly noteHebrew: string;
}

export interface AsaClass {
  readonly class: 'I' | 'II' | 'III' | 'IV' | 'V' | 'VI';
  readonly patient: string;
}

export interface OrifVsCrifEntry {
  readonly reduction: string;
  readonly incision: string;
  readonly visualization: string;
  readonly softTissueDamage: string;
  readonly infectionRisk: string;
  readonly indication: string;
}

export interface OrifVsCrifExample {
  readonly procedure: string;
  readonly category: string;
  readonly note?: string;
}

export interface OrifVsCrif {
  readonly ORIF: OrifVsCrifEntry;
  readonly CRIF: OrifVsCrifEntry;
  readonly examples: ReadonlyArray<OrifVsCrifExample>;
  readonly rehabImplication: string;
}

export interface ImNailBrand {
  readonly brand: string;
  readonly manufacturer: string;
  readonly lagScrew: string;
  readonly note: string;
}

export interface SutureSite {
  readonly site: string;
  readonly siteHebrew: string;
  readonly podStandard: readonly [number, number];
  readonly note: string;
}

export interface SutureModifiers {
  readonly prolong: ReadonlyArray<string>;
  readonly shorten: ReadonlyArray<string>;
  readonly borderlineProtocol: string;
  readonly steriStripPolicy: string;
  readonly weekendTrap: string;
}

export interface DvtPreset {
  readonly drug: string;
  readonly doseSC: string;
  readonly frequency: string;
  readonly durationDays: number;
  readonly noteHebrew: string;
}

export interface DvtRenalAdjustment extends DvtPreset {
  readonly criterion: string;
}

export interface DvtProphylaxisHipPostOp {
  readonly default: DvtPreset;
  readonly renalAdjustments: ReadonlyArray<DvtRenalAdjustment>;
}

export interface VancouverType {
  readonly type: 'A' | 'B1' | 'B2' | 'B3' | 'C';
  readonly location: string;
  readonly stemStability: string;
  readonly treatment: string;
}

export interface ImagingDiagnosis {
  readonly cause: string;
  readonly frequency: string;
  readonly trigger: string;
  readonly imaging: string;
  readonly labs: string;
}

export interface BedsideImagingRule {
  readonly scenario: string;
  readonly firstMove: string;
}

export const ORTHO_REFERENCE = {
  version: '1.0.0',
  lastUpdated: '2026-05-10',
  source: 'rehab-quickref + ortho-reference skills, SZMC geri-rehab convention',

  hipFractureProcedures: [
    {
      fractureLocation: 'Femoral neck (intracapsular)',
      subtype: 'Non-displaced (Garden I-II)',
      procedure: 'CRIF / cannulated screws',
      rationale: 'Preserve native head; AVN risk ~10-30% if delayed',
      approach: ['3 parallel screws, percutaneous'],
    },
    {
      fractureLocation: 'Femoral neck (intracapsular)',
      subtype: 'Displaced (Garden III-IV), low demand or >65-70',
      procedure: 'Hemiarthroplasty (usually bipolar)',
      rationale: 'Shorter OR, less blood loss, faster WB',
    },
    {
      fractureLocation: 'Femoral neck (intracapsular)',
      subtype: 'Displaced (Garden III-IV), high demand or 65-75 active',
      procedure: 'THA',
      rationale: 'Better long-term function, less acetabular wear',
    },
    {
      fractureLocation: 'Femoral neck (intracapsular)',
      subtype: 'Displaced + young (<55)',
      procedure: 'ORIF cannulated screws',
      rationale: 'Head preservation; revision later if needed',
    },
    {
      fractureLocation: 'Intertrochanteric (extracapsular)',
      subtype: 'Stable (2-part, AO 31-A1)',
      procedure: 'DHS',
      rationale: 'Lag screw allows controlled compression; cheap, well-studied',
    },
    {
      fractureLocation: 'Intertrochanteric (extracapsular)',
      subtype: 'Unstable (3-4 part, reverse oblique, AO 31-A2/A3)',
      procedure: 'IM nail (PFNA / TFN / Gamma)',
      rationale: "Load-sharing; doesn't depend on medial buttress",
    },
    {
      fractureLocation: 'Subtrochanteric (within 5cm below lesser troch)',
      subtype: 'Any',
      procedure: 'Long IM nail',
      rationale: 'DHS contraindicated, medial cortex disrupted, eccentric forces',
    },
    {
      fractureLocation: 'Pertrochanteric / peritrochanteric',
      subtype: 'Per stability',
      procedure: 'DHS or IM nail',
      rationale: 'Often synonymous with intertroch in op reports',
    },
  ],

  demandStratification: {
    purpose: 'Drives Hemi vs THA in displaced femoral neck',
    higherDemand: [
      'Community ambulator unaided',
      'ASA I-II',
      'No life-limiting comorbidity',
      'CFS 1-3',
      'Long life expectancy (above 10y)',
      'Working / driving / active',
    ],
    lowerDemand: [
      'Household ambulator with walker / cane',
      'ASA III-IV',
      'ESKD/HD, NYHA III-IV HF, advanced dementia, metastatic cancer',
      'CFS 5 or more',
      'Limited life expectancy (HD ~50% 5y survival; CFS 7 ~1-2y)',
      'Mostly seated, supervised mobility',
    ],
    noteHebrew: "מטופל על המודיאליזה = תפקודית 'low demand' גם אם גיל כרונולוגי לא מתאים.",
  },

  asaClasses: [
    { class: 'I', patient: 'Healthy, non-smoker, no/minimal alcohol' },
    { class: 'II', patient: 'Mild systemic disease (controlled HTN/DM, mild obesity, social drinker, smoker)' },
    { class: 'III', patient: 'Severe systemic disease, NOT incapacitating (poorly controlled DM/HTN, COPD on PRN O2, NYHA II HF, CKD 3-4, BMI 40 or more, MI more than 3mo)' },
    { class: 'IV', patient: 'Severe systemic disease, constant threat to life (MI within 3mo, NYHA III-IV, ESKD on HD, severe valve disease, sepsis, decompensated cirrhosis)' },
    { class: 'V', patient: 'Moribund, not expected to survive 24h without surgery' },
    { class: 'VI', patient: 'Brain-dead, organ donor' },
  ],
  asaSuffix: { E: 'Emergency (e.g., IIIE)' },
  asaWarning: "Don't confuse with ASA = aspirin. Same letters, different world.",

  orifVsCrif: {
    ORIF: {
      reduction: 'Open fracture site, see fragments directly, align by hand',
      incision: 'Larger, over fracture site',
      visualization: 'Direct vision',
      softTissueDamage: 'More',
      infectionRisk: 'Higher',
      indication: 'Articular fractures, complex patterns, failed CR',
    },
    CRIF: {
      reduction: 'Closed, fragments aligned by traction + manipulation under fluoroscopy, fracture site never opened',
      incision: 'Small / percutaneous, away from fracture',
      visualization: 'Image intensifier (C-arm)',
      softTissueDamage: 'Less',
      infectionRisk: 'Lower',
      indication: 'Reducible fractures with sufficient indirect imaging',
    },
    examples: [
      { procedure: 'Cannulated screws (non-displaced femoral neck)', category: 'CRIF (true)', note: '1cm stab wounds' },
      { procedure: 'DHS', category: 'ORIF (by convention)', note: 'Lateral incision opens femoral shaft for side plate; fracture itself reduced closed' },
      { procedure: 'IM nail', category: 'CRIF', note: 'Small entry at greater trochanter tip; fracture reduced on traction table' },
      { procedure: 'Hemi / THA', category: 'Neither, arthroplasty (replacement, not fixation)' },
    ],
    rehabImplication: 'CRIF means less soft tissue trauma, less post-op pain, faster mobilization, less wound concern at suture removal. ORIF (esp. DHS lateral incision) needs more day-1 wound attention.',
  },

  imNailBrands: [
    { brand: 'PFNA', manufacturer: 'Synthes', lagScrew: 'Helical blade (hammered, not drilled)', note: 'Compacts trabecular bone for grip in osteoporotic head. Classic geriatric nail.' },
    { brand: 'TFN', manufacturer: 'DePuy Synthes', lagScrew: 'Standard lag + anti-rotation screw', note: 'Older design, still common.' },
    { brand: 'TFNA', manufacturer: 'DePuy Synthes', lagScrew: 'Helical blade option', note: 'TFN updated to compete with PFNA.' },
    { brand: 'Gamma', manufacturer: 'Stryker', lagScrew: 'Lag screw', note: 'Most recognizable, oldest cephalomedullary design.' },
    { brand: 'InterTAN', manufacturer: 'Smith & Nephew', lagScrew: 'Two integrated lag screws', note: 'Better rotational control.' },
  ],
  imNailNote: "Brand specifics rarely change rehab management. Pull dimensions verbatim from op report (e.g., '170/10/120, Lag Screw 95, Distal Locking 40').",

  sutureTiming: [
    { site: 'Face / neck', siteHebrew: 'פנים / צוואר', podStandard: [5, 7], note: 'Cosmesis priority, scar track marks' },
    { site: 'Scalp', siteHebrew: 'קרקפת', podStandard: [7, 10], note: 'Hairline tension' },
    { site: 'Trunk / abdomen', siteHebrew: 'גו / בטן', podStandard: [10, 14], note: 'Standard window' },
    { site: 'Hip / proximal extremity', siteHebrew: 'ירך / גפה פרוקסימלית', podStandard: [10, 14], note: 'Hemi / ORIF / THA / DHS, typical rehab cohort' },
    { site: 'Spine (lumbar / thoracic)', siteHebrew: 'עמוד שדרה', podStandard: [14, 14], note: 'Deep closure, high tension' },
    { site: 'Knee / below', siteHebrew: 'ברך / מתחת', podStandard: [14, 14], note: 'Tension from walking' },
    { site: 'Foot', siteHebrew: 'כף רגל', podStandard: [14, 21], note: 'Slowest healing zone' },
  ],
  sutureModifiers: {
    prolong: [
      'Steroids / immunosuppression (+3-7d)',
      'Diabetes, esp. A1c above 8 (+3-7d)',
      'Malnutrition (albumin under 3.0)',
      'Smoking / vascular disease',
      'Wound under tension / dehiscence risk',
      'Active infection signs (drainage, erythema)',
    ],
    shorten: [
      'Cosmetic priority (face) means earlier removal + Steri-Strips',
      'Healing well, low tension means standard window',
    ],
    borderlineProtocol: 'Remove alternating sutures first. If wound stays approximated 24-48h then remove rest. If gapping then leave + consult ortho.',
    steriStripPolicy: 'Apply Steri-Strips for 5-7 days post-removal if any tension or healing-speed concern.',
    weekendTrap: 'Friday SZMC suture removal: confirm order is scheduled FOR Friday, not punted to weekend coverage. Past day 14 = avoidable suture-track marks + minor infection risk.',
  },

  dvtProphylaxisHipPostOp: {
    default: {
      drug: 'Enoxaparin',
      doseSC: '40mg',
      frequency: 'daily',
      durationDays: 35,
      noteHebrew: 'ENOXAPARIN 40mg SC פעם ביום למשך 35 ימים מהניתוח.',
    },
    renalAdjustments: [
      {
        criterion: 'CrCl under 30 OR HD',
        drug: 'Enoxaparin',
        doseSC: '20mg',
        frequency: 'daily',
        durationDays: 35,
        noteHebrew: 'ENOXAPARIN 20mg SC פעם ביום (CrCl נמוך מ-30 או המודיאליזה).',
      },
      {
        criterion: 'Active bleeding risk OR contraindication to LMWH',
        drug: 'UFH',
        doseSC: '5000 units',
        frequency: 'BID-TID',
        durationDays: 35,
        noteHebrew: 'UFH 5000 יחידות SC פעמיים-שלוש ביום.',
      },
    ],
  },

  vancouverPeriprostheticFemur: [
    { type: 'A', location: 'Trochanteric region (AG = greater, AL = lesser)', stemStability: 'N/A', treatment: 'Conservative or wires/cables' },
    { type: 'B1', location: 'Around stem', stemStability: 'Stable', treatment: 'ORIF + cables / locking plate (keep stem)' },
    { type: 'B2', location: 'Around stem', stemStability: 'Loose', treatment: 'Revision arthroplasty (replace stem)' },
    { type: 'B3', location: 'Around stem', stemStability: 'Loose + poor bone stock', treatment: 'Revision + possibly proximal femoral replacement' },
    { type: 'C', location: 'Distal to stem tip', stemStability: 'N/A', treatment: 'ORIF (locking plate)' },
  ],
  vancouverNote: "B1 vs B2 distinction changes the operation. Need full-length femur film + sometimes CT. Don't tell ortho 'Vancouver B' without specifying, they need it for OR planning.",

  postOpImagingDifferential: [
    { cause: 'Dislocation (THA more than Hemi)', frequency: 'Most common acute', trigger: 'Sudden pain after movement, leg shortened + rotated', imaging: 'AP + lateral hip stat', labs: 'None, clinical Dx' },
    { cause: 'Periprosthetic fracture', frequency: 'Common after fall', trigger: 'Fall in PT, new pain', imaging: 'AP hip + full-length femur', labs: 'None' },
    { cause: 'Periprosthetic joint infection', frequency: 'Subacute (weeks 4-12)', trigger: 'Increasing pain or wound issues; fever may be absent', imaging: 'AP + lateral hip; compare to immediate post-op film', labs: 'ESR + CRP. If both elevated then joint aspiration BEFORE any abx.' },
    { cause: 'Aseptic loosening', frequency: 'Late (months-years)', trigger: 'Pain only with weight-bearing, no rest pain', imaging: 'AP + lateral, compare to post-op for radiolucent lines over 2mm', labs: 'ESR + CRP (rule out PJI)' },
    { cause: 'DHS screw cutout', frequency: 'Weeks 4-8 post-DHS', trigger: 'New groin pain, leg shortened', imaging: 'AP hip, screw migrated superomedially', labs: 'None' },
  ],
  imagingPearls: [
    'Plain film is INSENSITIVE for early infection. Normal X-ray does NOT rule out PJI.',
    "Always pull immediate post-op film for comparison. Radiology won't volunteer it. In Chameleon, 2 clicks back through imaging tab.",
    'Posterior dislocation (90%): femoral head sits posterosuperior to acetabulum on AP.',
    'Loosening: radiolucent line over 2mm at bone-cement / bone-implant interface, especially progressive on serial films. Stem subsidence for cementless stems.',
    'DHS screw cutout: lag screw migrates superomedially. Risk factor: tip-apex distance over 25mm on original post-op film.',
    'PJI lytic signs (periosteal reaction, focal osteolysis, lucent line widening) are LATE findings.',
  ],

  bedsideImagingRules: [
    { scenario: 'Acute new hip pain + deformity / shortening', firstMove: 'Stat AP + lateral hip, rule out dislocation or periprosthetic fracture before mobilizing further' },
    { scenario: 'Subacute pain weeks 4-12, no trauma', firstMove: 'AP + lateral, compare to immediate post-op. ESR + CRP. If past 12 weeks and markers up then joint aspiration before biopsy/revision talk' },
    { scenario: 'Wound issues (drainage, dehiscence, erythema) past POD 7', firstMove: 'Plastics + ortho consults same day. Do NOT start oral abx empirically, cripples culture yield if revision needed' },
    { scenario: 'Pain only with weight-bearing, no rest pain', firstMove: 'More likely loosening than infection. Same imaging, expedite ortho follow-up rather than infection workup' },
    { scenario: 'Falls in PT, especially within 4 weeks post-op', firstMove: "Repeat hip + full-length femur X-ray, even if 'no pain' on around-the-clock paracetamol, undisplaced periprosthetic fractures get missed" },
  ],
} as const;

export type OrthoReference = typeof ORTHO_REFERENCE;
